# Generated by Django 5.0.2 on 2024-02-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_notion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notion',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
